dist: bionic
group: travis_latest

os: linux
language: python

matrix:
  include:
    - env: CC=gcc
    - env: CC=clang

install:
  - pip install meson ninja
  - wget https://github.com/frida/frida/releases/download/12.11.12/frida-gum-devkit-12.11.12-linux-x86_64.tar.xz -O frida-gum.tar.xz && tar xJvf frida-gum.tar.xz

script:
  - meson build
  - meson compile -C build
  - meson test -C build

branches:
  only:
    - staging
    - trying
    - master